version: '3.8'
services:
  php:
    image: repox/laravel-dev-php:8.0
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/docker-vhost.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:8.0
    links:
      - php
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/mysql.conf.d/bind.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apidevs
      MYSQL_USER: apidevs
      MYSQL_PASSWORD: apidevs
  composer:
    image: repox/laravel-dev-php:8.0
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['/usr/bin/composer']  
  artisan:
    image: repox/laravel-dev-php:8.0
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']